### ISSUE TITLE
How to add your lib to my SBT file?

### ISSUE THREAD

**Issue by nghuuphuoc** [coreyauger/scala-js-pdf#2]
As title.

**Comment by coreyauger** [comment]
You can add the project as a dependency to one that you are working on.  This might be the best way at the start .. at least until the project gets further along.  

Another way would be to use `sbt publishLocal` and then include the artefact in your other project like so

`"io.surfkit" %%%  "scala-js-pdf"  % "0.1-SNAPSHOT"`

I will add some documentation when I get some time to focus on this project.

**Comment by nghuuphuoc** [comment]
I tried to add `"io.surfkit" %%% "scala-js-pdf" % "0.1-SNAPSHOT"` to my dependencies but after importing the project, the IDE (IntelliJ IDEA) informs the following issue

```
Error:Error while importing SBT project:
[info] Resolving org.iq80.leveldb#leveldb;0.5 ...
...
[info] Resolving org.scala-sbt#control;0.13.11 ...
[trace] Stack trace suppressed: run 'last stargazerJs/*:update' for the full output.
[trace] Stack trace suppressed: run 'last stargazerJs/*:ssExtractDependencies' for the full output.
[error] (stargazerJs/*:update) sbt.ResolveException: unresolved dependency: 
io.surfkit#scala-js-pdf_sjs0.6_2.11;0.1-SNAPSHOT: not found
[error] (stargazerJs/*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: 
io.surfkit#scala-js-pdf_sjs0.6_2.11;0.1-SNAPSHOT: not found
[error] Total time: 20 s, completed Jun 17, 2016 12:31:54 PM
See complete log in <a href="/Users/phuocnguyen/Library/Logs/IdeaIC2016.1/sbt.last.log">/Users/phuocnguyen/Library/Logs/IdeaIC2016.1/sbt.last.log</a>
```

It couldn't find `io.surfkit#scala-js-pdf_sjs0.6_2.11;0.1-SNAPSHOT`.
Do I miss anything?

**Comment by coreyauger** [comment]
Hi @nghuuphuoc ,

You need to publish the package to your local ivy cache.  I would recommend having a read through here: http://www.scala-sbt.org/0.13/docs/Publishing.html

This will push the compiled depedancy to your local ivy cache and sbt will be able to find it.  The dissadvantage to this is that if you make any change to that lib (which you will almost certainly have to) .. you will have to republish with `sbt publishLocal` every time. 

Alternatively if you include the project as a compiled dependancy ... you can make changes right in your IDE and have them be detected and recompiled.

Hope that helps you get on track :)

**Comment by coreyauger** [comment]
Just to be clear..
You would go into the `scala-js-pdf` folder from the checked out git repo and type `sbt publishLocal` to get a libarby that is stored in your local ivy2 cache.

But like I said the library may not even compile yet at this stage..  PR's are welcome ;)
